### ISSUE TITLE
Не запускает

### ISSUE THREAD

**Issue by allexkap** [stebochek/2d_platformer_#1]
При запуске выдает следующее, что мне делать ?????/
```
pygame 2.4.0 (SDL 2.26.4, Python 3.9.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/walex/.tmp/2d_platformer/main.py", line 77, in <module>
    game = Game()
  File "/home/walex/.tmp/2d_platformer/main.py", line 20, in __init__
    self.level_music = pygame.mixer.Sound('./sounds/level.mp3')
pygame.error: mixer not initialized
```
Помогите пожалуйста, я буду очень большим фанатом вашей игры (если вы мне поможете ехе)

**Comment by allexkap** [comment]
Я нашел команды на стаковерфлов и теперь другая ошибка, помогите пожалуйста!!!
```
pygame 2.4.0 (SDL 2.26.4, Python 3.9.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/walex/.tmp/2d_platformer/main.py", line 75, in <module>
    pygame.mixer.init()
pygame.error: dsp: No such audio device
```

**Comment by allexkap** [comment]
пон

**Comment by allexkap** [comment]
...
